name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shellcheck:
    name: Check shell scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run sh-checker
      uses: luizm/action-sh-checker@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        sh_checker_only_diff: true
        sh_checker_comment: true
